services:
  kanidm:
    image: kanidm/server:1.3.2
    ports:
      - 8443:8443
    volumes:
      - ./config/server.toml:/data/server.toml:ro
      - ./certs/kanidm.local.key:/data/key.pem:ro
      - ./certs/kanidm.local.crt:/data/chain.pem:ro